### ISSUE TITLE
Out of range in metadata_label_json

### ISSUE THREAD

**Issue by santitham** [blockfrost/blockfrost-python#9] opened 2021-11-24 12:48 UTC
Got the following error when using the label beyond integer range, for example, '11111111111', '9223372036854775799' when using api.metadata_label_json (Python interface, version 0.3.3). Note that these are the resulting label obtained from api.metadata_labels.

ApiError: {'status_code': 400, 'error': 'Bad Request', 'message': 'Missing, out of range or malformed label.'}

Suspecting that it is because of string to integer, or integer to string conversions. Or unvalidated metadata labels. Or uncleaned metadata.

**Comment by mathiasfrohlich** [comment] 2021-11-24 15:29
@santitham Thanks for bringing this to my attention.  
Yes, I can confirm the issue.  

This does not appear to be a Python SDK issue but a backend API issue.  
Have tested this outside the Python SDK with the following `curl` commands to illustrate the problem.  

This work:
```sh
curl -X GET \
  'https://cardano-mainnet.blockfrost.io/api/v0/metadata/txs/labels/1990' \
  -H 'project_id: {REDACTED}'
  
 Response:
 [{"tx_hash":"19e20c46fd73dc483fd45aee7e8df0a88917ac404143b63787bd39f535bdbb96","json_metadata":[{"eng":{"title":"Welcome to NUTS!","content":["For more information, visit our website www.stakenuts.com."]}}]}]%    
```

This gives an error:
```sh
curl -X GET \
  'https://cardano-mainnet.blockfrost.io/api/v0/metadata/txs/labels/11111111111' \
  -H 'project_id: {REDACTED}'

Response:
{"status_code":400,"error":"Bad Request","message":"Missing, out of range or malformed label."}
```

@mmahut will you have a look at this.

**Comment by mathiasfrohlich** [comment] 2021-12-07 09:09
@mmahut Any update on this issue?

**Comment by 1000101** [comment] 2021-12-09 23:40
> @mmahut Any update on this issue?

Hi @mathiasfrohlich we're just releasing an API fix addressing this issue (along with other goodies). So sorry it took so long, we encountered some unrelated stoppers along the way.

It has already been deployed to testnet and you can verify the fix [here](https://cardano-testnet.blockfrost.io/api/v0/metadata/txs/labels/9223372036854775799).

As per mainnet, we will roll-out new version in under 24hrs from now.

Thanks once again for the report @santitham, and sorry for the delay!

Cheers!

**Comment by 1000101** [comment] 2021-12-12 21:51
@mathiasfrohlich @santitham could you please verify it everything works correctly for you?

Thanks a million!

**Comment by mathiasfrohlich** [comment] 2021-12-13 07:29
Hey @1000101 

I have verified and all seems to be working now.
Thanks for fixing the issue.

And thanks to @santitham for raising the issue.

I am closing this issue, if anything feel free to reopen and comment.

**Closed by mathiasfrohlich** 2021-12-13 07:29 UTC
